### ISSUE TITLE
FLEX弹性盒模型布局

### ISSUE THREAD

**Issue by CarryWang** [CarryWang/Note#10]
# 一、Flex布局是什么？

Flex是Flexible Box的缩写，意为"弹性布局"，用来为盒状模型提供最大的灵活性。
任何一个容器都可以指定为Flex布局。

```css
.box{
  display: flex;
}
```

![](https://llp0574.github.io/img/flex-2.gif)

**注意**，设为Flex布局以后，子元素的`float`、`clear`和`vertical-align`属性将失效。

# 二、基本概念

采用Flex布局的元素，称为Flex容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为Flex项目（flex item），简称"项目"。

![css3-flexbox-model](https://cloud.githubusercontent.com/assets/12207994/24540080/32bf665c-1624-11e7-9406-e343436ae2e0.jpg)

容器默认存在两根轴：水平的主轴（main axis）和垂直的交叉轴（cross axis）。主轴的开始位置（与边框的交叉点）叫做**main start**，结束位置叫做**main end**；交叉轴的开始位置叫做**cross start**，结束位置叫做**cross end**。

项目默认沿主轴排列。单个项目占据的主轴空间叫做**main size**，占据的交叉轴空间叫做**cross size**。

# 三、容器的属性

以下6个属性设置在容器上。

- flex-direction
- flex-wrap
- flex-flow
- justify-content
- align-items
- align-content

## 3.1 flex-direction属性

`flex-direction`属性决定主轴的方向（即项目的排列方向）。

```css
.box {
  flex-direction: row | row-reverse | column | column-reverse;
}
```

它可能有4个值。

- row（默认值）：主轴为水平方向，起点在左端。
- row-reverse：主轴为水平方向，起点在右端。
- column：主轴为垂直方向，起点在上沿。
- column-reverse：主轴为垂直方向，起点在下沿。

**默认状态下，容器里的每一个元素都会从左至右沿着主轴排列**。这也是为什么一旦 display: flex 生效，所有块都会默认排列在一个水平线上。

 `flex-direction` 可以让你旋转主轴。

```css
.box{
  display: flex;
  flex-direction: column;
}
```

![](https://llp0574.github.io/img/flex-4.gif)

这里有一个很重要的区别：flex-direction: column 并不是把块从主轴移到交叉轴上排列，**而是让主轴自身从水平变成垂直。**

 `flex-direction` 的另外两个选项值：`row-reverse` 和 `column-reverse`。

![](https://llp0574.github.io/img/flex-5.gif)

## 3.2 flex-wrap属性

默认情况下，项目都排在一条线（又称"轴线"）上。`flex-wrap`属性定义，如果一条轴线排不下，如何换行。

![](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071006.png)

```css
.box{
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```

它可能取三个值。

（1）`nowrap`（默认）：不换行。
![](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071007.png)

（2）wrap：换行，第一行在上方。
![](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071008.jpg)

（3）wrap-reverse：换行，第一行在下方。
![](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071009.jpg)

## 3.3 flex-flow

`flex-flow`属性是`flex-direction`属性和`flex-wrap`属性的简写形式，默认值为`row nowrap`。

```css
.box {
  flex-flow: <flex-direction> || <flex-wrap>;
}
```

## 3.4 justify-content属性

justify-content属性定义了项目在主轴上的对齐方式。

.box {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}

它可能取5个值，具体对齐方式与轴的方向有关。下面假设主轴为从左到右。

- flex-start（默认值）：左对齐
- flex-end：右对齐
- center： 居中
- space-between：两端对齐，项目之间的间隔都相等。
- space-around：每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍。

![](https://llp0574.github.io/img/flex-6.gif)

最后一个注意点：**记住` justify-content` 是沿着主轴工作的，而 `flex-direction` 则是用来改变主轴的。**当看到下一个属性的时候就会发现这点很重要。

## 3.5 align-items属性

`align-items`属性定义项目在交叉轴上如何对齐

```css
.box {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```

它可能取5个值。具体的对齐方式与交叉轴的方向有关，下面假设交叉轴从上到下。

- flex-start：交叉轴的起点对齐。
- flex-end：交叉轴的终点对齐。
- center：交叉轴的中点对齐。
- baseline: 项目的第一行文字的基线对齐。
- stretch（默认值）：如果项目未设置高度或设为auto，将占满整个容器的高度。

![](https://llp0574.github.io/img/flex-8.gif)

`stretch` 状态下，每一项都会占满整个交叉轴，而 `baseline` 状态下，将按照段落标签的底部对齐（图中每个块里的数字均由p标签包含，此处就是按照p标签的底部对齐）。

**注意` align-items: stretch`，必须将每一块的高度设置为` auto`，否则高度属性（height）就会将 `stretch` 的作用给覆盖掉。**

对于`baseline `来说，要意识到如果去掉段落标签，就将按照每个块的底部对齐（译者注：只要是元素标签内没有文字或者子标签内没有文字，均会按照每个块的底部对齐），像下面这样：

![](https://llp0574.github.io/img/flex-9.png)

为了更清楚地阐明主轴和交叉轴的区别，下面我们来把 justify-content 和 align-items 合在一起，看看在 flex-direction 两种值的作用下轴心有什么不一样：

![](https://llp0574.github.io/img/flex-10.gif)

**取值为 row 时，每个块会按照一个水平的主轴进行排列，为 column 时，它们就会按照一个垂直的主轴向下排列。**

虽然这些块在两种情况下都可以水平或者垂直居中，但这两者是不可以相互转化的！

## 3.6 align-content属性

`align-content`属性定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。\

.box {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}

![](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071012.png)

该属性可能取6个值。

- flex-start：与交叉轴的起点对齐。
- flex-end：与交叉轴的终点对齐。
- center：与交叉轴的中点对齐。
- space-between：与交叉轴两端对齐，轴线之间的间隔平均分布。
- space-around：每根轴线两侧的间隔都相等。所以，轴线之间的间隔比轴线与边框的间隔大一倍。
- stretch（默认值）：轴线占满整个交叉轴。

# 四、项目的属性

以下6个属性设置在项目上。

- order
- flex-grow
- flex-shrink
- flex-basis
- flex
- align-self

## 4.1 order属性

`order`属性定义项目的排列顺序。数值越小，排列越靠前，默认为0。

```css
.item {
  order: <integer>;
}
```

## 4.2 flex-grow属性

flex-grow属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大

```csss
.item {
  flex-grow: <number>; /* default 0 */
}
```
