### ISSUE TITLE
使用官方脚手架Create-React-App

### ISSUE THREAD

**Issue by CarryWang** [CarryWang/Note#7]
# 使用官方脚手架Create-React-App

> Create React App is the best way to start building a new React single page application. It sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.

React的官方脚手架[Create React App](https://github.com/facebookincubator/create-react-app)
不需要任何配置一步创建APP。

## 起步
**Create React App** 以下简称 **CRA**

### 安装
全局安装：
```sh
npm install -g create-react-app
```

### 创建APP
创建一个新APP，运行：
```sh
create-react-app my-app
cd my-app
```

CRA会在当前文件件创建一个叫 `my-app` 的文件夹，目录下会包含以下东西：

```
my-app/
  README.md
  node_modules/
  package.json
  .gitignore
  public/
    favicon.ico
    index.html
  src/
    App.css
    App.js
    App.test.js
    index.css
    index.js
    logo.svg
```
没有繁琐的配置，也没有复杂的文件结构，你只需要在当前文件夹运行：
### `npm start` 

打开浏览器[http://localhost:3000](http://localhost:3000) 就能看到已经构建完成的应用。

除了这点，CRA已经做好了热更新，只要你的编辑的代码有改动，他会自动reload。

**注意：**  使用**webstorm**时，有时常常编辑更改代码后却迟迟不见热更新，你只需要在**Systeam Settings**里找到**Use safe write**选项，把它前面的勾勾去掉就好了。

之后每次修改后 `ctrl + s` CRA就会自动帮你更新啦。

当你需要部署生产环境，你只需要运行：
### `npm run build` 

CRA会创建一个叫`build`的文件夹，里面是已经压缩合并好的代码。

Your app is ready to be deployed!

## 用户指南
介绍一些常用的扩展

## 目录结构

应用创建后你的目录结构应该是这样的：

```
my-app/
  README.md
  node_modules/
  package.json
  .gitignore
  public/
    favicon.ico
    index.html
  src/
    App.css
    App.js
    App.test.js
    index.css
    index.js
    logo.svg
```
对于项目构建，这些文件必须存在：
* `public/index.html` 这是页面模板；
* `src/index.js` 这是JS入口文件。

你可是删除或者重命名其他文件。

你可能会在 `src`文件夹里添加很多子文件夹. 为了更快的编译，只有 `src` 里的文件会被Webpack编译。

你需要 **把JS和CSS文件放进`src`文件夹** ， 否则Webpack会无视它们。

## 安装依赖
你可能会用到其他的依赖包，运行：

```sh
npm install --save <library-name>
```

## Post-Processing CSS

CRA已经自动帮你添加了PostCSS的[ Autoprefixer](https://github.com/postcss/autoprefixer)，你不需要担心。

就像这样：
```css
.App {
  display: flex;
  flex-direction: row;
  align-items: center;
}
```
变成这样：
```css
.App {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
      -ms-flex-direction: row;
          flex-direction: row;
  -webkit-box-align: center;
      -ms-flex-align: center;
          align-items: center;
}
```

## 添加CSS预处理器（Sass，Less）

以Sass为例，安装：
```sh
npm install node-sass --save-dev
```
打开`package.json`，找到`scripts`：
```diff
"scripts": {
+    "build-css": "node-sass src/ -o src/",
+    "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive",
     "start": "react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test --env=jsdom",
```

你会发现你在`start`时没法`watch-css`，所以我们安装这个：
```sh
npm install --save-dev npm-run-all
```

改变`statr`和`build`命令：

```diff
"scripts": {
     "build-css": "node-sass src/ -o src/",
     "watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive",
-    "start": "react-scripts start",
-    "build": "react-scripts build",
+    "start-js": "react-scripts start",
+    "start": "npm-run-all -p watch-css start-js",
+    "build": "npm run build-css && react-scripts build",
     "test": "react-scripts test --env=jsdom",
     "eject": "react-scripts eject"
   }
```
